### ISSUE TITLE
Make me owner of Discord server pls?

### ISSUE THREAD

**Issue by JonathanTheInsane** [theishiopian/ForageCraft#13]
@theishiopian I was previously the owner of the Discord server and I accidentally transferred ownership to you, and I want it back. I'm contacting you here because you're almost never on Discord so cheers to that.

**Comment by theishiopian** [comment]
Lol, ok, sure. I actually have been on a bit recently. You just have to find me 😉

**Comment by theishiopian** [comment]
Ok, you got your server back, thanks for providing it!
