### ISSUE TITLE
Decorative stick block dropped upon breaking the entity

### ISSUE THREAD

**Issue by Omnimetatron** [theishiopian/ForageCraft#14]
The title explains most of it, but I will add that the stick block entity is dropping a stick as expected in addition to dropping itself. Aside from the funky pink box, it is currently an unlimited source of sticks.

**Comment by JonathanTheInsane** [comment]
I'm not worried about textures, since the stick block is incomplete. However, I have identified that breaking the block in survival mode does indeed drop the block entity. I will revise this code and inform Theishiopian if he needs to make changes that I cannot.

**Comment by theishiopian** [comment]
The block is not supposed to have an inventory model, nor should it drop itself. I'll fix this later tonight.

**Comment by JonathanTheInsane** [comment]
@theishiopian The code in the class for the block is correct in dropping the stick. However, there appears to be no code blocking the dropping of the block entity itself. Try to see if you can change anything with the "onBlockDestroyedByPlayer" portion of the BlockStick class.

**Comment by theishiopian** [comment]
The thing is, the rock doesn't have the same problem from what I remember from my testing. Might be due to the way I implemented the rocks though.

**Comment by JonathanTheInsane** [comment]
I think the rocks are implemented the same way last time I checked
