### ISSUE TITLE
Ablity to disable sticks/rocks worldgen?

### ISSUE THREAD

**Issue by GeekyNinja** [theishiopian/ForageCraft#16]
Hi, wondering if there's an ability or there will be a future ability to disable the stick and rock worldgen?

Currently running 1.12.1 BETA for Minecraft 1.11.2

Thanks.

**Comment by theishiopian** [comment]
The rock/stick generation is experimental, as such it can't be disabled. This will change when all the kinks have been ironed out.

**Comment by theishiopian** [comment]
These features are experimental and cannot be disabled. This will change once these features are complete and work flawlessly.
