### ISSUE TITLE
Rocks generate on beaches. 

### ISSUE THREAD

**Issue by theishiopian** [theishiopian/ForageCraft#17]
They're not supposed to do that. Naughty rocks.

**Comment by theishiopian** [comment]
Should I replace the rocks on beaches with seashells?

**Comment by JonathanTheInsane** [comment]
@theishiopian That would be preferred but rocks may also show up sometimes on beaches but not as often. Maybe change the spawn rate of the rocks?

**Comment by theishiopian** [comment]
Fair point. Also, what would seashells be used for? Arrowheads maybe?

**Comment by JonathanTheInsane** [comment]
@theishiopian I believe arrowheads could work. Try adding them and if you come up with other shit then add that.

**Comment by theishiopian** [comment]
FFS github
