### ISSUE TITLE
Right-clicking sticks on ground removes a stone item from inventory

### ISSUE THREAD

**Issue by Omnimetatron** [theishiopian/ForageCraft#18]
http://imgur.com/a/jhdcc

The images shown in the above ling are a before and after of me right-clicking a stick block. Notice how a stone has been removed from the stack on the hotbar and is now hovering alongside the stick.

**Comment by Omnimetatron** [comment]
And now I can't replicate the behaviour. Very strange...

**Comment by theishiopian** [comment]
Well, we can reopen this if the behavior comes back.
