### ISSUE TITLE
Holy shit: A lot of Deprecated Stuff

### ISSUE THREAD

**Issue by JonathanTheInsane** [theishiopian/ForageCraft#22]
Yo if we don't get the newer methods for some of this shit, we're fucked in the near future.

**Comment by theishiopian** [comment]
A lot of the deprecated methods are in use because I couldn't find an alternative. I'll look again though, and if you find any non deprecated solutions please document them for future reference.

**Comment by JonathanTheInsane** [comment]
@theishiopian ya

**Comment by theishiopian** [comment]
That being said, there may be new ways of doing things in the newer forge. Besides, those methods were deprecated for a reason right?

**Comment by JonathanTheInsane** [comment]
@theishiopian Exactly. Though the methods themselves might be completely unsupported in the future.

**Comment by JonathanTheInsane** [comment]
I'll work on the JEI deprecated methods for now.

**Comment by theishiopian** [comment]
Ill take a second look at the methods in the rock entities, as that will make things easier when I add more rocks.

**Comment by JonathanTheInsane** [comment]
It doesn't really seem like we need to fix these. Everything is working fine, and if things change in the future, we can simply change what's in the code to adapt to Minecraft updates.
