### ISSUE TITLE
rocks generate on giant mushrooms

### ISSUE THREAD

**Issue by Octopork** [theishiopian/ForageCraft#24]
1.12.3 beta

Rocks can generate on at the very least brown giant mushrooms, didn't see them on red but probably worth checking too.

**Comment by theishiopian** [comment]
I'll fix this when I get home

-----Original Message-----

**Comment by theishiopian** [comment]
Can you provide the seed/coords, for testing purposes? will make this a lot easier :)

**Comment by Octopork** [comment]
7670100323430838974  

That will work, not my seed but mushroom biome that has multiple occurrences

**Comment by theishiopian** [comment]
Awesome, Ill get on this Asap!

**Comment by JonathanTheInsane** [comment]
Well this looks frightening
[http://i.imgur.com/LtaVhGR.jpg](http://i.imgur.com/LtaVhGR.jpg)

**Comment by JonathanTheInsane** [comment]
@Octopork Fixed
