### ISSUE TITLE
[1.12.1] ModBlocks registry needs to be completely changed

### ISSUE THREAD

**Issue by JonathanTheInsane** [theishiopian/ForageCraft#27]
FUCK
http://www.minecraftforge.net/forum/topic/58996-112-gameregistryregister-not-working/
http://mcforge.readthedocs.io/en/latest/concepts/registries/

**Comment by theishiopian** [comment]
I'm aware of this, its the same for items.

**Comment by theishiopian** [comment]
This issue is CLOSED, I thought I made that clear GitHub!
