### ISSUE TITLE
Rock/Stick bounding boxes

### ISSUE THREAD

**Issue by KingPhygieBoo** [theishiopian/ForageCraft#32]
The bounding boxes of sticks and rocks when placed into the world are a full block, when they could be the size of themselves.

**Comment by JonathanTheInsane** [comment]
Gonna add the hitboxes sooner or later.

**Comment by theishiopian** [comment]
^^^

**Comment by JonathanTheInsane** [comment]
Stalled for the time being until other issues are resolved.

**Comment by theishiopian** [comment]
This shouldnt be too hard, I'll look into it.

**Comment by theishiopian** [comment]
Alright, pretty much fixed.
