### ISSUE TITLE
Shading problems with Scarecrow.

### ISSUE THREAD

**Issue by KingPhygieBoo** [theishiopian/ForageCraft#34]
It's different depending on the direction, one has a problem with the arm, and the other's are with the head.
![2017-09-30_18 13 40](https://user-images.githubusercontent.com/17862210/31050300-f7865276-a60b-11e7-90ac-a91b9909375f.png)

**Comment by theishiopian** [comment]
I am aware of this issue, I'm unsure of how to fix it.

**Comment by KingPhygieBoo** [comment]
Make it take the neighboring block's light

**Comment by JonathanTheInsane** [comment]
@KingPhygieBoo are you able to do that with this mod and make a pull request?

**Comment by KingPhygieBoo** [comment]
I can attempt to do so later, yes.

**Comment by JonathanTheInsane** [comment]
@KingPhygieBoo Alright I'm looking forward to that. If you are unable to do it, let me know.
