### ISSUE TITLE
Stick can be middle clicked, and has a broken item model.

### ISSUE THREAD

**Issue by KingPhygieBoo** [theishiopian/ForageCraft#35]
This should probably give you a Vanilla stick on middle click.
![2017-09-30_18 01 09](https://user-images.githubusercontent.com/17862210/31050306-1e743b0a-a60c-11e7-9af5-f68347824b68.png)

**Comment by JonathanTheInsane** [comment]
Since this version of ForageCraft is still in beta, I will stall the correction of this bug, since players normally will not need to hold sticks by hand in survival, and there is no way to obtain the model itself in survival.

**Comment by JonathanTheInsane** [comment]
Any block can be middle-clicked, btw. There's no changing that.

**Comment by theishiopian** [comment]
Actually, I'm considering giving that block a name and model, so creative mode players can use it as decoration

**Comment by JonathanTheInsane** [comment]
Alright
