### ISSUE TITLE
Sticks can float in 1.12

### ISSUE THREAD

**Issue by KingPhygieBoo** [theishiopian/ForageCraft#37]
Don't know if this is intended or not, figured I'd report it anyway.
![2017-09-30_18 24 11](https://user-images.githubusercontent.com/17862210/31050320-9995fb20-a60c-11e7-92ec-e7cbf42f1070.png)

**Comment by JonathanTheInsane** [comment]
Let's focus on the other major bugs before fixing this one.

**Comment by theishiopian** [comment]
The rock part is fixed in 1.12
