### ISSUE TITLE
Rocks generate on blocks they shouldn't

### ISSUE THREAD

**Issue by KingPhygieBoo** [theishiopian/ForageCraft#38]
This poor guy's house has a rock in it.
![2017-09-30_18 45 56](https://user-images.githubusercontent.com/17862210/31050463-08e609ae-a610-11e7-9ea6-927531be6033.png)

**Comment by theishiopian** [comment]
Ooops

**Comment by JonathanTheInsane** [comment]
@theishiopian I got it don't worry

**Comment by theishiopian** [comment]
nah, i'll get it tonight, I want you to find the JEI problem.

**Comment by theishiopian** [comment]
Fuckin hell github, close the damn issue!

**Comment by JonathanTheInsane** [comment]
Lol nice

**Comment by theishiopian** [comment]
DO you know how to close via commit properly? This is driving me mad!

**Comment by JonathanTheInsane** [comment]
@theishiopian yes. You put “Fixes #whatever” in the commit message

**Comment by JonathanTheInsane** [comment]
“Resolves” doesn’t do squat in GitHub
