### ISSUE TITLE
JEI vanilla item descriptions not registered

### ISSUE THREAD

**Issue by theishiopian** [theishiopian/ForageCraft#39]
Even after re-running setupDecompWorkspace, jei vanilla item descriptions are still non functional on my machine. Once we get this fixed, I will release the first 1.12 alpha.

**Comment by JonathanTheInsane** [comment]
Fuck me I’ll fix it tomorrow. Going to sleep. Night.

**Comment by theishiopian** [comment]
gotcha

Ill fix some of the other stuff tonight.

**Comment by JonathanTheInsane** [comment]
They seem to be working now lmao
