### ISSUE TITLE
Unforseen cascading worldgen lag

### ISSUE THREAD

**Issue by JonathanTheInsane** [theishiopian/ForageCraft#45]
I don't even know where this came from. Probably from the update of Forge.

**Comment by theishiopian** [comment]
Huh, interesting. Can you provide more details? I can ask the guys on the MC forums about this, they usually have advanced knowledge about the changes between updates.

**Comment by JonathanTheInsane** [comment]
I haven't encountered this issue for a while though. Interesting.

**Comment by theishiopian** [comment]
I may have found the solution to this, I need to take a look at it when I'm less foggy. 
http://www.minecraftforge.net/forum/topic/60721-1121-how-would-i-prevent-cascading-worldgen-lag-during-worldgen/

**Comment by JonathanTheInsane** [comment]
That is so long and vague to read. I’m sick and have school and majorly
stressed out so I’ll leave that to you.

**Comment by theishiopian** [comment]
I think this is fixed, closing for now. I will reopen if there are reports of more lag.
