### ISSUE TITLE
snow

### ISSUE THREAD

**Issue by AlexRover** [theishiopian/ForageCraft#50]
Hello, here I see such a picture everywhere, over the grass this was not, maybe it can be somehow corrected? Thank you in advance, with the coming)))
![2017-12-30_03 36 40](https://user-images.githubusercontent.com/34899332/34447990-b22f1e16-ed13-11e7-9dd2-f3d0e0f6cb2c.png)

**Comment by theishiopian** [comment]
I believe @JonathanTheInsane implemented the fix for this, if not I'll do it.

**Comment by JonathanTheInsane** [comment]
Yeah I fixed it. It’s part of the topSolid bug I fixed
