### ISSUE TITLE
gradlew eclipse no longer generates eclipse folder

### ISSUE THREAD

**Issue by SansIsTyping** [theishiopian/ForageCraft#6]
In order to fix this, I will need to use the eclipse folder given in the ForgeMDK. Sorry to any inconvenience for anyone using eclipse.

**Comment by theishiopian** [comment]
I wish we could add the label WTF graddle

**Comment by theishiopian** [comment]
Will get to this ASAP

**Comment by theishiopian** [comment]
Not sure why, but it works now
