### ISSUE TITLE
Unforseen hiccups in MC1.11 ForageCraft update

### ISSUE THREAD

**Issue by JonathanTheInsane** [theishiopian/ForageCraft#7]
--------------------------------------------------
__@Override__
@SideOnly(Side.CLIENT)
public AxisAlignedBB __getCollisionBoundingBox__(IBlockState state, World world, BlockPos pos) {
    return getSelectedBoundingBox(state, world, pos);
}
--------------------------------------------------

Anything in bold is what is causing errors or is not working.

**Comment by theishiopian** [comment]
Working on it right now

**Comment by JonathanTheInsane** [comment]
Will close issue when 1.11 is confirmed working.
