### ISSUE TITLE
2 branches enter, one branch leaves.

### ISSUE THREAD

**Issue by theishiopian** [theishiopian/ForageCraft#8]
It seems that Jonathan and I both updated to 1.11 separately. To resolve this, I've created a separate branch called 1.11_alt so we can resolve the discrepancies between the two.

**Comment by JonathanTheInsane** [comment]
K I'll just make some adjustments. I made no actual updates in my 1.11 branch, just attempted to update it.

**Comment by theishiopian** [comment]
I think I did it, check it on your end, and then we can close this thing!
